from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_login_view, name='admin_login'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('logout/', views.admin_logout, name='admin_logout'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/<int:employee_id>/update/', views.update_employee, name='update_employee'),
    path('employees/<int:employee_id>/delete/', views.delete_employee, name='delete_employee'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.add_customer, name='add_customer'),
    path('customers/<int:pk>/delete/', views.delete_customer, name='delete_customer'),
    path('drivers/', views.driver_list, name='driver_list'),
    path('drivers/add/', views.add_driver, name='add_driver'),
    path('drivers/<int:driver_id>/update/', views.update_driver, name='update_driver'),
    path('drivers/<int:driver_id>/delete/', views.delete_driver, name='delete_driver'),
    path('drivers/<int:driver_id>/toggle-status/', views.toggle_driver_status, name='toggle_driver_status'),
    path('vehicle-types/', views.vehicle_type_list, name='vehicle_type_list'),
    path('add_vehicle_type/', views.add_vehicle_type, name='add_vehicle_type'),
    path('delete_vehicle_type/<int:pk>/', views.delete_vehicle_type, name='delete_vehicle_type'),
    path('vehicle_type_list_view/', views.vehicle_type_list_view, name='vehicle_type_list_view'),
    path('loads/', views.load_list, name='load_list'),
    path('loads/<int:load_id>/requests/', views.load_requests_api, name='load_requests_api'),
    path('loads/<int:load_id>/requests/<int:request_id>/accepted/', views.accept_load_request_with_assignment, name='accept_load_request_with_assignment'),
    path('requests/<int:request_id>/update/', views.update_request_status, name='update_request_status'),
     path('api/vendors/<int:vendor_id>/vehicles/', views.vendor_vehicles_api, name='vendor_vehicles_api'),
    path('api/vendors/<int:vendor_id>/drivers/', views.vendor_drivers_api, name='vendor_drivers_api'),
    path('loads/add/', views.add_load, name='add_load'),
    path('loads/<int:load_id>/requests/<int:request_id>/accepted/', views.accept_load_request, name='accept_load_request'),
    path('loads/<int:load_id>/requests/<int:request_id>/rejected/', views.reject_load_request, name='reject_load_request'),
    path('loads/<int:load_id>/delete/', views.delete_load, name='delete_load'),
    path('loads/<int:load_id>/update-status/', views.update_load_status, name='update_load_status'),
    path('loads/customer/<int:customer_id>/details/', views.get_customer_details, name='get_customer_details'),
    path('vendor/', views.vendor_list, name='vendor_list'),
    path('vendor/add/', views.add_vendor, name='add_vendor'),
    path('vendor/<int:vendor_id>/delete/', views.delete_vendor, name='delete_vendor'),
    path('vendor/<int:vendor_id>/get/', views.get_vendor, name='get_vendor'),
    path('vendor/<int:vendor_id>/toggle-status/', views.toggle_vendor_status, name='toggle_vendor_status'),
    path('vehicle/', views.vehicle_list, name='vehicle_list'),
    path('vehicle/add/', views.add_vehicle, name='add_vehicle'),
    path('vehicle/<int:vehicle_id>/delete/', views.delete_vehicle, name='delete_vehicle'),
    path('vehicle/<int:vehicle_id>/toggle-status/', views.toggle_vehicle_status, name='toggle_vehicle_status'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/data/', views.get_profile_data, name='get_profile_data'),
    path('loads/add-driver/', views.add_load_driver, name='quick_add_driver'),
    path('loads/add-vehicle/', views.add_load_vehicle, name='quick_add_vehicle'),

    path('trips/', views.trip_management, name='trip_management'),
    path('api/trip/<int:trip_id>/details/', views.get_trip_details_api, name='get_trip_details_api'),
    path('api/trip/<int:trip_id>/update-status/', views.update_trip_status_api, name='update_trip_status_api'),
    path('api/trip/<int:trip_id>/add-comment/', views.add_trip_comment_api, name='add_trip_comment'),
    path('api/trip/<int:trip_id>/comments/', views.get_trip_comments_api, name='get_trip_comments'),
    path('api/trip/<int:trip_id>/unread-count/', views.get_unread_comments_count_api, name='unread_comments_count'),
    path('api/trip/<int:trip_id>/close/', views.close_trip_api, name='close_trip_api'),
    path('api/trip/<int:trip_id>/upload-lr/', views.upload_lr_document_api, name='upload_lr_document'),
    path('api/trip/<int:trip_id>/view-lr/', views.view_lr_document_api, name='view_lr_document'),
    path('api/trip/<int:trip_id>/upload-pod/', views.upload_pod_document_api, name='upload_pod_document_api'),


path('payments/', views.payment_management, name='payment_management'),
path('api/payment/<int:trip_id>/details/', views.get_payment_details_api, name='get_payment_details_api'),
path('api/payment/<int:trip_id>/mark-first-half-paid/', views.mark_first_half_paid_api, name='mark_first_half_paid'),
path('api/payment/<int:trip_id>/mark-final-payment-paid/', views.mark_final_payment_paid_api, name='mark_final_payment_paid'),

    
    
    
]

