# Generated by Django 5.2.1 on 2025-11-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_customuser_name_alter_customuser_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
