# Generated by Django 5.2.1 on 2025-11-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0005_remove_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(default='TEMP00000', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tds_declaration',
            field=models.FileField(default='defaults/tds_dummy.pdf', upload_to='tds_documents/'),
            preserve_default=False,
        ),
    ]
