# Generated by Django 5.2.1 on 2025-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tds_declaration',
            field=models.FileField(blank=True, null=True, upload_to='tds_documents/'),
        ),
    ]
