# Generated by Django 5.2.1 on 2025-11-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0011_customuser_full_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username', '-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
