# Generated by Django 5.2.1 on 2025-11-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0012_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
