# Generated by Django 5.2.1 on 2025-11-13 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0014_customuser_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='driver_documents/pan/', verbose_name='PAN Card Document')),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='driver_documents/aadhar/', verbose_name='Aadhar Card Document')),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='driver_documents/rc/', verbose_name='RC Document')),
                ('profile_photo', models.ImageField(blank=True, default='driver_photos/default_driver.png', null=True, upload_to='driver_photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_trips', models.IntegerField(default=0)),
                ('completed_trips', models.IntegerField(default=0)),
                ('pending_trips', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(help_text='Vendor who owns this driver', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
