# Generated by Django 5.2.1 on 2025-11-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0016_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('time', models.TimeField(help_text='Pickup/Delivery time')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in tons', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per ton', max_digits=10)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loads', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(help_text='Customer for this load', on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='logistics_app.customer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='logistics_app.vehicletype')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'ordering': ['-created_at'],
            },
        ),
    ]
