# Generated by Django 5.2.1 on 2025-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0017_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.CharField(help_text='Weight exactly as entered (e.g. 10 Ton, 20T, 15.5, etc.)', max_length=50),
        ),
    ]
