# Generated by Django 5.2.1 on 2025-11-14 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0018_alter_load_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='load',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='logistics_app.customer'),
        ),
        migrations.AlterField(
            model_name='load',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price per ton (₹)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='load',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.CharField(help_text='e.g. 10 Ton, 20T, 15.5 Heavy, 8 Ton Urgent', max_length=50),
        ),
    ]
