# Generated by Django 5.2.1 on 2025-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0019_alter_load_created_by_alter_load_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('traffic_person', 'Traffic Person'), ('vendor', 'Vendor'), ('user', 'User')], default='traffic_person', help_text='User role in the system', max_length=20),
        ),
    ]
