# Generated by Django 5.2.1 on 2025-11-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0020_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('heavy_truck', 'Heavy Truck'), ('medium_truck', 'Medium Truck'), ('light_truck', 'Light Truck')], default='heavy_truck', max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG')], default='diesel', max_length=10)),
                ('insurance_doc', models.FileField(blank=True, null=True, upload_to='vehicles/insurance/')),
                ('rc_doc', models.FileField(blank=True, null=True, upload_to='vehicles/rc/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
