# Generated by Django 5.2.1 on 2025-11-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0033_tripcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
