# Generated by Django 5.2.1 on 2026-01-02 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0033_holdingcharge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holdingcharge',
            new_name='logistics_a_load_id_7c8855_idx',
            old_name='logistics_app_holdingcharge_load_created_idx',
        ),
        migrations.RenameIndex(
            model_name='holdingcharge',
            new_name='logistics_a_trip_st_c84287_idx',
            old_name='logistics_app_holdingcharge_trip_stage_idx',
        ),
        migrations.AlterField(
            model_name='load',
            name='holding_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total additional charges for holding the shipment (auto-calculated)', max_digits=14, verbose_name='Total Holding Charges'),
        ),
        migrations.AlterField(
            model_name='load',
            name='holding_charges_added_at',
            field=models.DateTimeField(blank=True, help_text='When the first holding charge was added', null=True, verbose_name='Holding Charges Added At'),
        ),
        migrations.AlterField(
            model_name='load',
            name='holding_charges_added_at_status',
            field=models.CharField(blank=True, help_text='The trip status at which first holding charge was added', max_length=20, null=True, verbose_name='Trip Status When Charges Added'),
        ),
    ]
