# Generated by Django 5.2.1 on 2025-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0035_customuser_fcm_token_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='tracking_details',
            field=models.TextField(blank=True, help_text='Tracking details added by vendor during POD upload or later', null=True),
        ),
    ]
