# Generated by Django 5.2.1 on 2025-12-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0036_load_tracking_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='tracking_details',
        ),
    ]
