# Generated by Django 5.2.1 on 2025-12-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0037_remove_load_tracking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='tracking_details',
            field=models.TextField(blank=True, help_text='Tracking details added by vendor during POD upload or later', null=True),
        ),
    ]
