# Generated by Django 5.2.1 on 2025-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0039_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('lr_uploaded', 'LR Uploaded'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('pod_uploaded', 'POD Uploaded'), ('payment_completed', 'Payment Completed')], default='pending', max_length=20),
        ),
    ]
