# Generated by Django 5.2.1 on 2025-12-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0040_alter_load_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='first_half_payment',
        ),
        migrations.RemoveField(
            model_name='load',
            name='first_half_payment_at',
        ),
    ]
