# Generated by Django 5.2.1 on 2025-12-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0041_remove_load_first_half_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason for putting the trip on hold', null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('lr_uploaded', 'LR Uploaded'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('pod_uploaded', 'POD Uploaded'), ('payment_completed', 'Payment Completed'), ('hold', 'Hold')], default='pending', max_length=20),
        ),
    ]
