# Generated by Django 5.2.1 on 2026-01-02 05:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0042_load_hold_at_load_hold_reason_alter_load_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='holding_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charges for holding the shipment', max_digits=14, verbose_name='Holding Charges'),
        ),
        migrations.AddField(
            model_name='load',
            name='holding_charges_added_at',
            field=models.DateTimeField(blank=True, help_text='When the holding charges were added', null=True, verbose_name='Holding Charges Added At'),
        ),
        migrations.AddField(
            model_name='load',
            name='holding_charges_added_at_status',
            field=models.CharField(blank=True, help_text='The trip status at which holding charges were added', max_length=20, null=True, verbose_name='Trip Status When Charges Added'),
        ),
    ]
