# Generated by Django 5.2.1 on 2026-01-02 05:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0043_load_holding_charges_load_holding_charges_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='first_half_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='First payment installment - 90% of total freight', max_digits=14, verbose_name='First Half Payment (90%)'),
        ),
        migrations.AddField(
            model_name='load',
            name='second_half_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Second payment installment - 10% of total freight', max_digits=14, verbose_name='Second Half Payment (10%)'),
        ),
    ]
