# Generated by Django 5.2.1 on 2026-01-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0044_load_first_half_payment_load_second_half_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
