# Generated by Django 5.2.1 on 2026-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0046_alter_load_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('loaded', 'Reach Loading Point'), ('lr_uploaded', 'LR Uploaded'), ('in_transit', 'In Transit'), ('unloading', 'Reach Unloading Point'), ('pod_uploaded', 'POD Uploaded'), ('payment_completed', 'Payment Completed'), ('hold', 'Hold')], default='pending', max_length=20),
        ),
    ]
