# Generated by Django 5.2.1 on 2026-01-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0034_rename_logistics_app_holdingcharge_load_created_idx_logistics_a_load_id_7c8855_idx_and_more'),
        ('logistics_app', '0048_add_holding_charges_meta'),
    ]

    operations = [
    ]
