# Generated by Django 5.2.1 on 2026-01-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0049_merge_20260102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number for the vendor', max_length=20, null=True, unique=True, verbose_name='Vehicle Registration Number'),
        ),
    ]
