# Generated by Django 5.2.1 on 2026-01-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0050_customuser_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vehicle_number',
        ),
    ]
