# Generated by Django 5.2.1 on 2026-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0051_remove_customuser_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='tracking_details_image',
            field=models.ImageField(blank=True, help_text='Image evidence of tracking details', null=True, upload_to='pod_documents/tracking_images/'),
        ),
    ]
