# Generated by Django 5.2.1 on 2026-01-05 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0052_load_tracking_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='before_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount expected before manual adjustment', max_digits=14),
        ),
        migrations.AddField(
            model_name='load',
            name='confirmed_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confirmed amount actually paid for final settlement', max_digits=14, null=True),
        ),
    ]
