# Generated by Django 5.2.1 on 2026-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0053_load_before_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acc_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
