# Generated by Django 5.2.1 on 2026-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0054_customuser_acc_no_customuser_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='payment_adjustment_reason',
            field=models.TextField(blank=True, help_text='Reason for payment adjustment (increase/decrease)', null=True),
        ),
    ]
