# Generated by Django 5.2.1 on 2026-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0055_load_payment_adjustment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='first_half_payment_paid',
            field=models.BooleanField(default=False, help_text='Whether the first half payment has been paid', verbose_name='First Half Payment Paid'),
        ),
        migrations.AddField(
            model_name='load',
            name='first_half_payment_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the first half payment was marked as paid', null=True, verbose_name='First Half Payment Paid At'),
        ),
    ]
