# Generated by Django 5.2.1 on 2026-01-06 05:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0056_load_first_half_payment_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='to_location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
