# Generated by Django 5.2.1 on 2026-01-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0057_vehicle_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alternate_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
