# Generated by Django 5.2.1 on 2026-01-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0058_customuser_alternate_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=2.0, help_text='TDS percentage rate', max_digits=5)),
            ],
            options={
                'verbose_name': 'TDS Rate',
                'verbose_name_plural': 'TDS Rate',
            },
        ),
    ]
