# Generated by Django 5.2.1 on 2026-01-06 08:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0059_tdsrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='apply_tds',
            field=models.BooleanField(default=False, help_text='Check if TDS should be applied to this load', verbose_name='Apply TDS'),
        ),
        migrations.AddField(
            model_name='load',
            name='user_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Additional price field for user reference', max_digits=14, null=True, verbose_name='User Price (Optional)'),
        ),
    ]
