# Generated by Django 5.2.1 on 2026-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0060_load_apply_tds_load_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
