# Generated by Django 5.2.1 on 2026-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0061_load_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pod_received_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when POD was physically received', null=True, verbose_name='POD Received At'),
        ),
    ]
