# Generated by Django 5.2.1 on 2026-01-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0062_load_pod_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('forgot_password', 'Forgot Password')], default='login', max_length=20),
        ),
    ]
