# Generated by Django 5.2.1 on 2026-01-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0063_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'ordering': ['-created_at']},
        ),
    ]
