# Generated by Django 5.2.1 on 2026-01-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0064_alter_phoneotp_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person_phone',
        ),
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='logistics_app.customer')),
            ],
        ),
    ]
