# Generated by Django 5.2.1 on 2026-01-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0065_remove_customer_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontactperson',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='logistics_app.customer'),
        ),
    ]
