# Generated by Django 5.2.1 on 2026-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0066_alter_customercontactperson_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='If true, user cannot access API routes'),
        ),
    ]
