# Generated by Django 5.2.1 on 2026-01-09 12:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0067_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='user_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='User-specific amount for this load', max_digits=14, null=True, verbose_name='User Amount'),
        ),
    ]
