# Generated by Django 5.2.1 on 2026-01-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0068_load_user_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_cheque',
            field=models.FileField(blank=True, null=True, upload_to='bank_cheques/'),
        ),
    ]
