# Generated by Django 5.2.1 on 2026-01-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0069_customuser_aadhaar_card_customuser_bank_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/'),
        ),
    ]
