# Generated by Django 5.2.1 on 2026-02-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0070_customuser_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingcharge',
            name='trip_stage',
            field=models.CharField(choices=[('trip_requested', 'Trip Requested'), ('trip_confirmed', 'Trip Confirmed'), ('reached_loading_point', 'Reached at Loading point'), ('upload_lr', 'Upload LR'), ('in_transit', 'In transit'), ('reached_unloading_point', 'Reached at unloading point'), ('unloading_completed', 'Unloading completed'), ('pod_pending', 'POD status - Pending'), ('pod_received_at_office', 'POD status - received at rotra office'), ('balance_pending', 'Balance pending'), ('balance_hold', 'Balance hold'), ('balance_paid', 'Balance paid'), ('trip_closed', 'Trip closed')], help_text='The trip stage/status at which this charge was applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('trip_requested', 'Trip Requested'), ('trip_confirmed', 'Trip Confirmed'), ('reached_loading_point', 'Reached at Loading point'), ('upload_lr', 'Upload LR'), ('in_transit', 'In transit'), ('reached_unloading_point', 'Reached at unloading point'), ('unloading_completed', 'Unloading completed'), ('pod_pending', 'POD status - Pending'), ('pod_received_at_office', 'POD status - received at rotra office'), ('balance_pending', 'Balance pending'), ('balance_hold', 'Balance hold'), ('balance_paid', 'Balance paid'), ('trip_closed', 'Trip closed')], default='trip_requested', max_length=30),
        ),
    ]
