# Generated by Django 5.2.1 on 2026-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0071_alter_holdingcharge_trip_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pod_status',
            field=models.CharField(choices=[('pod_pending', 'POD Pending'), ('upload_soft_copy', 'Upload Soft Copy'), ('received_at_office', 'Received at RoTra Office'), ('received_at_unloading', 'POD Received at Unloading Point')], default='pod_pending', help_text='Current status of POD processing', max_length=25, verbose_name='POD Status'),
        ),
    ]
