# Generated by Django 5.2.1 on 2026-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0072_load_pod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='current_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when current location was last updated', null=True),
        ),
    ]
