# Generated by Django 5.2.1 on 2026-02-06 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0073_load_current_location_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, help_text='Where the vehicle is currently located', max_length=255, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='from_location',
            field=models.CharField(blank=True, help_text='Starting location or home base of vehicle', max_length=255, null=True, verbose_name='From Location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='to_location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of destination/routes this vehicle covers', size=None, verbose_name='Destinations'),
        ),
    ]
