# Generated by Django 5.2.1 on 2026-02-06 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0074_vehicle_current_location_vehicle_from_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='from_location',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='to_location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
