# Generated by Django 5.2.1 on 2026-02-19 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0075_remove_vehicle_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='before_payment_amount',
        ),
        migrations.RemoveField(
            model_name='load',
            name='confirmed_paid_amount',
        ),
        migrations.RemoveField(
            model_name='load',
            name='final_payment',
        ),
        migrations.RemoveField(
            model_name='load',
            name='first_half_payment',
        ),
        migrations.RemoveField(
            model_name='load',
            name='first_half_payment_paid',
        ),
        migrations.RemoveField(
            model_name='load',
            name='first_half_payment_paid_at',
        ),
        migrations.RemoveField(
            model_name='load',
            name='payment_adjustment_reason',
        ),
        migrations.RemoveField(
            model_name='load',
            name='second_half_payment',
        ),
        migrations.AlterField(
            model_name='holdingcharge',
            name='trip_stage',
            field=models.CharField(choices=[('trip_requested', 'Trip Requested'), ('trip_confirmed', 'Trip Confirmed'), ('reached_loading_point', 'Reached at Loading point'), ('upload_lr', 'Upload LR'), ('in_transit', 'In transit'), ('reached_unloading_point', 'Reached at unloading point'), ('unloading_completed', 'Unloading completed'), ('pod_pending', 'POD status - Pending'), ('pod_received_at_office', 'POD status - received at rotra office'), ('trip_closed', 'Trip closed')], help_text='The trip stage/status at which this charge was applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('trip_requested', 'Trip Requested'), ('trip_confirmed', 'Trip Confirmed'), ('reached_loading_point', 'Reached at Loading point'), ('upload_lr', 'Upload LR'), ('in_transit', 'In transit'), ('reached_unloading_point', 'Reached at unloading point'), ('unloading_completed', 'Unloading completed'), ('pod_pending', 'POD status - Pending'), ('pod_received_at_office', 'POD status - received at rotra office'), ('trip_closed', 'Trip closed')], default='trip_requested', max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this payment', max_digits=14)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when payment was recorded')),
                ('description', models.TextField(blank=True, help_text='Description or note for this payment (e.g., "First half payment", "Adjustment", etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this payment record was last updated')),
                ('load', models.ForeignKey(help_text='The load/trip this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics_app.load')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin/user who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['load', 'payment_date'], name='logistics_a_load_id_3bb70a_idx'), models.Index(fields=['payment_date'], name='logistics_a_payment_ad0cd5_idx')],
            },
        ),
    ]
