# Generated by Django 5.2.1 on 2026-02-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0076_remove_load_before_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when location was last updated', null=True),
        ),
    ]
